controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    # left_wheel_names: ['base_link_to_front_left_wheel','base_link_to_bottom_left_wheel']
    # right_wheel_names: ['base_link_to_front_right_wheel','base_link_bottom_right_wheel']

    left_wheel_names: ['base_link_to_front_left_wheel']
    right_wheel_names: ['base_link_to_front_right_wheel']
    
    wheel_separation: 0.154 #1.49
    wheel_radius: 0.03 #0.035

    use_stamped_vel: false

    